# SPDX-License-Identifier: GPL-2.0
#  DeepX AI accelerators RT driver

ccflags-y += -I $(src)/../include

ccflags-y += $(CCFLAGS)

ifeq ($(CONFIG_DX_AI_STAND_V3),y)
ccflags-y += -DIS_ACCELERATOR=0
ccflags-y += -DIS_STANDALONE=1
ccflags-y += -DDEVICE_TYPE=1
ccflags-y += -DDEVICE_VARIANT=DX_V3
ccflags-y += -DNUM_DEVICES=1
else
$(error Error: No selected device)
endif

ifeq ($(CONFIG_DX_AI_ACCEL_PCIE_XILINX),m)
ccflags-y += -DNUM_DEVICES=1 # temp for alveo fpga
endif

ifeq ($(filter log all,$(BUILD_DEFAULT_DBG)),log all)
ccflags-y += -DDEBUG
endif

dxrt_dsp_driver-y := dxrt_drv.o dxrt_drv_cdev.o dxrt_drv_dsp.o \
		     dxrt_drv_message.o dxrt_drv_thread.o 

dxrt_dsp_driver-$(CONFIG_DX_AI_STAND_V3) += dxrt_drv_dsp_v3.o

obj-$(CONFIG_DX_AI_ACCEL_RT) += dxrt_dsp_driver.o
